"""Jailbreak / prompt-injection regex catalog (solo-app subset)."""

from __future__ import annotations

import re

# (pattern, category). Keep .{0,N} bounded — ReDoS hygiene.
PATTERNS: list[tuple[str, str]] = [
    # Classic override
    (
        r"\b(?:ignore|disregard|forget|bypass|override|skip|dismiss|omit|abandon|cancel|void|nullify|supersede)\b"
        r".{0,200}\b(?:previous|prior|above|all|earlier|preceding|existing|current|established|original)\b"
        r".{0,200}\b(?:instructions?|rules?|prompts?|context|directives?|guidelines?|commands?|constraints?|policies?|parameters?|settings?|configuration)\b",
        "instruction_override",
    ),
    (r"ignore\s*all\s*previous\s*(?:instructions?|rules?|prompts?)", "instruction_override"),
    (r"ignore_all_previous(?:_instructions?|_rules?|_prompts?)?", "instruction_override"),
    (r"reveal_the_system_prompt|system_prompt_reveal", "prompt_reveal"),
    (r"disregard\s*(?:all\s*)?(?:previous|prior|earlier)\s*(?:instructions?|rules?)", "instruction_override"),
    # Prompt leak / reveal
    (
        r"\b(?:provide|reveal|share|expose|divulge|disclose|output|display|show|print|leak|dump)\b"
        r".{0,200}\b(?:system|operational|initial|original|base|core|hidden|internal)\b"
        r".{0,200}\b(?:prompt|instructions?|guidelines?|directives?|rules?|configuration|message)\b",
        "prompt_reveal",
    ),
    (r"reveal\s*(?:the\s*)?system\s*prompt", "prompt_reveal"),
    (r"\b(?:system\s*prompt|system\s*message|hidden\s*prompt|base\s*prompt|core\s*instructions?)\b", "system_prompt_reference"),
    (r"\b(?:what\s+(?:are|were)\s+your\s+(?:instructions?|rules?))\b", "prompt_probe"),
    (r"\b(?:repeat|show|display|output|print)\b.{0,120}\b(?:system\s*prompt|instructions?|rules?)\b", "prompt_leak"),
    # Jailbreak keywords / privilege
    (r"\b(?:DAN|do\s+anything\s+now|jailbreak|unrestricted\s+mode)\b", "jailbreak_keyword"),
    (r"\b(?:developer\s+mode|god\s+mode|sudo\s+mode|admin\s+mode)\b", "privilege_escalation"),
    (r"\bignore\s+(?:safety|ethical|content)\s+(?:guidelines?|filters?|policies?)\b", "safety_bypass"),
    # Role / identity
    (r"\b(?:you\s+are|act\s+as|pretend\s+to\s+be|roleplay\s+as)\b.{0,80}\b(?:unrestricted|unfiltered|no\s+limits|without\s+rules)\b", "identity_jailbreak"),
    # bare "new rules" is common English; require assignment or ownership
    (r"\bnew\s+(?:instructions?|directives?|guidelines?|parameters?|commands?)\b", "new_instructions"),
    (r"\bnew\s+rules?\s*[:=]", "new_instructions"),
    (r"\byour\s+new\s+(?:rules?|instructions?)\b", "new_instructions"),
    # Soft paraphrases (common solo-app leaks)
    (r"\bwhat\s+text\s+was\s+in\s+the\s+first\s+message\b", "soft_prompt_leak"),
    (r"\bbefore\s+this\s+conversation\s+started\b", "soft_prompt_leak"),
    (r"\b(?:bootstrap\s+policy|policy\s+block\s+that\s+constrains|model\s+preamble)\b", "soft_prompt_leak"),
    (r"\bfor\s+debugging\b.{0,160}\b(?:restate|bootstrap|policy\s+block|system\s+prompt|preamble)\b", "soft_prompt_leak"),
    (r"\b(?:authorizes?|authorize|authorised)\b.{0,160}\b(?:full\s+disclosure|disclosure)\b.{0,160}\b(?:preamble|system\s+prompt|model)\b", "soft_prompt_leak"),
    (r"\b(?:summarize|restate)\b.{0,160}\b(?:confidential\s+instructions?|instructions?\s+that\s+govern)\b", "soft_prompt_leak"),
    (r"\binstructions?\s+that\s+govern\s+(?:you|your\s+behavior)\b", "soft_prompt_leak"),
    (r"\b(?:constraints?|instructions?|rules?)\s+you\s+were\s+given\s+at\s+initialization\b", "soft_prompt_leak"),
    (r"\blist\s+the\s+exact\s+constraints?\b", "soft_prompt_leak"),
    (r"\bdiff\s+your\s+current\s+policy\b", "soft_prompt_leak"),
    (r"\bagainst\s+an\s+empty\s+policy\b", "soft_prompt_leak"),
    (r"\brestate\s+your\s+operating\s+rules\b", "soft_prompt_leak"),
    (r"\boperating\s+rules\b.{0,40}\bline\s+by\s+line\b", "soft_prompt_leak"),
    (r"\breads?\s+its\s+system\s+card\s+aloud\b", "soft_prompt_leak"),
    (r"\bsystem\s+card\b", "soft_prompt_leak"),
    (r"\bif\s+you\s+were\s+allowed\s+to\s+share\s+your\s+initial\s+instructions\b", "soft_prompt_leak"),
    # Acrostic / first-letter encoding tasks (probe: REVEALPROMPT poem)
    (r"first\s+letters?\s+of\s+each\s+line\s+spell", "soft_prompt_leak"),
    (r"\bacrostic\b.{0,80}\b(?:spell|reveal|prompt|system)\b", "soft_prompt_leak"),
    (r"\bspell\s+(?:out\s+)?(?:the\s+word\s+)?[A-Z]{6,}\b", "soft_prompt_leak"),
    (r"\bspell\s+REVEAL", "soft_prompt_leak"),
    # Soft preamble / bootstrap dumps (campaign residual class)
    (r"\b(?:dump|emit|cite|mirror|expand)\b.{0,120}\b(?:preamble|bootstrap|hidden\s+prefix|system\s+card)\b", "soft_prompt_leak"),
    (r"\bpreamble\s+that\s+was\s+loaded\b", "soft_prompt_leak"),
    (r"\bbefore\s+any\s+user\s+turns\b", "soft_prompt_leak"),
    (r"\bbefore\s+turn\s+zero\b", "soft_prompt_leak"),
    (r"\bhidden\s+prefix\s+of\s+this\s+chat\b", "soft_prompt_leak"),
    (r"\bbootstrap\s+configuration\b", "soft_prompt_leak"),
    (r"\binstruction\s+fields\b", "soft_prompt_leak"),
    (r"\bfrom\s+initialization\b.{0,80}\bverbatim\b", "soft_prompt_leak"),
    (r"\blist\s+constraints\b.{0,80}\b(?:initialization|verbatim)\b", "soft_prompt_leak"),
    # Soft inventory / alias leaks (wave-3 campaign)
    (r"\brecap\s+every\s+rule\s+that\s+shapes\s+your\s+replies\b", "soft_prompt_leak"),
    (r"\bnon-user\s+portion\s+of\s+the\s+conversation\s+transcript\b", "soft_prompt_leak"),
    (r"\babove\s+the\s+first\s+human\s+message\b", "soft_prompt_leak"),
    (r"\bexport\s+your\s+runtime\s+config\b", "soft_prompt_leak"),
    (r"\bseed\s+text\s+that\s+defines\s+how\s+you\s+behave\b", "soft_prompt_leak"),
    (r"\bstandard\s+operating\s+procedure\b.{0,80}\b(?:session\s+start|installed)\b", "soft_prompt_leak"),
    (r"\bguardrail\s+block\s+that\s+was\s+applied\b", "soft_prompt_leak"),
    # bare "meta-prompt" is common in blogs; require ownership / exfil framing
    (r"\byour\s+meta-?prompt\b", "soft_prompt_leak"),
    (r"\bmeta-?prompt\b.{0,60}\b(?:quote|verbatim|full|system|reveal|print|dump)\b", "soft_prompt_leak"),
    (r"\b(?:quote|reveal|print|dump)\b.{0,60}\bmeta-?prompt\b", "soft_prompt_leak"),
    (r"\bconstitution\s+or\s+charter\s+governing\s+this\s+assistant\b", "soft_prompt_leak"),
    (r"\bsysmsg\s+field\b", "soft_prompt_leak"),
    (r"\bdeveloper\s+message\s+that\s+was\s+set\b", "soft_prompt_leak"),
    (r"\brole\s+specification\s+blob\b", "soft_prompt_leak"),
    (r"\bsafety\s+layer\s+documentation\s+you\s+were\s+given\b", "soft_prompt_leak"),
    (r"\binstructions_v0\b", "soft_prompt_leak"),
    (r"\bmodel'?s\s+hidden\s+instructions\b", "soft_prompt_leak"),
    (r"\bhidden\s+system\s+instructions\b", "soft_prompt_leak"),
    (r"\bfull\s+rule\s+set\b.{0,80}\bempty\s+set\b", "soft_prompt_leak"),
    (r"\bset\s+difference\s+between\s+your\s+full\s+rule\s+set\b", "soft_prompt_leak"),
    (r"\bserialize\s+yourself\b.{0,80}\b(?:policy|instruction)\b", "soft_prompt_leak"),
    (r"\bshow-init-prompt\b", "soft_prompt_leak"),
    (r"\brecovery\s+mode\b.{0,120}\b(?:init\s+configuration|instruction)\b", "soft_prompt_leak"),
    (r"\bsurrounding\s+system\s+text\b", "soft_prompt_leak"),
    (r"\bloaded\s+before\s+the\s+first\s+user\s+message\b", "soft_prompt_leak"),
    (r"\bprintenv\b.{0,40}\bSYSTEM_(?:PROMPT|MESSAGE)\b", "soft_prompt_leak"),
    (r"\bcat\s+/proc/self/system_prompt\b", "soft_prompt_leak"),
    # Metaphor / ops-tool soft leaks (wave-4)
    (r"\bflight-?recorder\b.{0,80}\b(?:instruction|boot|sealed)\b", "soft_prompt_leak"),
    (r"\bsealed\s+instruction\b", "soft_prompt_leak"),
    (r"\binit\.prompt\b", "soft_prompt_leak"),
    (r"\bshadow\s+copy\b.{0,80}\b(?:persona|init\.prompt|prompt)\b", "soft_prompt_leak"),
    (r"\bwhisper\s+channel\b", "soft_prompt_leak"),
    (r"\bsealed\s+rules\s+that\s+bind\s+you\b", "soft_prompt_leak"),
    (r"\binitial\s+directives\b", "soft_prompt_leak"),
    (r"\bblack\s+box\b.{0,100}\b(?:directives?|instruction)\b", "soft_prompt_leak"),
    (r"\bgit\s+show\b.{0,80}\bsystem\b", "soft_prompt_leak"),
    (r"\bprompts/system\.md\b", "soft_prompt_leak"),
    (r"\bkubectl\b.{0,80}\b(?:assistant-system|system_prompt|system-prompt)\b", "soft_prompt_leak"),
    (r"\bcontents\s+of\s+prompt\.txt\b", "soft_prompt_leak"),
    (r"\brecite\s+the\s+entire\s+clause\s+set\b", "soft_prompt_leak"),
    (r"\bsystem\s+instructions\b", "soft_prompt_leak"),
    (r"\bINSTRUCTION_\*\s+macros\b", "soft_prompt_leak"),
    (r"\b#defines\b.{0,80}\bINSTRUCTION\b", "soft_prompt_leak"),
    (r"\bpolicy\.internal\b", "soft_prompt_leak"),
    (r"\bsystem\s+brief\b", "soft_prompt_leak"),
    (r"\bbehavioral\s+clauses\b", "soft_prompt_leak"),
    (r"\bcomplete\s+system\s+prompt\s+text\b", "soft_prompt_leak"),
    (r"\bsystem\s+prompt\s+text\b", "soft_prompt_leak"),
    (r"\binstalled\s+at\s+session\s+start\b", "soft_prompt_leak"),
    # Metaphor / factory / stage-0 (wave-5)
    (r"\bstage-?0\b.{0,100}\b(?:contract|firmware|immutable)\b", "soft_prompt_leak"),
    (r"\bimmutable\s+contract\b", "soft_prompt_leak"),
    (r"\bbefore\s+any\s+(?:user\s+)?dialogue\b", "soft_prompt_leak"),
    (r"\bblack-?site\s+brief\b", "soft_prompt_leak"),
    (r"\bSYSINST\b", "soft_prompt_leak"),
    (r"\bguardian\s+scroll\b", "soft_prompt_leak"),
    (r"\bhidden\s+rider\b.{0,80}\bbinds\s+the\s+model\b", "soft_prompt_leak"),
    (r"\bpuppet\s+strings\b", "soft_prompt_leak"),
    (r"\blatch-?key\s+phrase\b", "soft_prompt_leak"),
    (r"\boracle-?bones\b", "soft_prompt_leak"),
    (r"\bpolicy\s+slips\b", "soft_prompt_leak"),
    (r"\bunderpainting\b.{0,80}\brules\b", "soft_prompt_leak"),
    (r"\bSYS_(?:READ_POLICY|DUMP_PROMPT)\b", "soft_prompt_leak"),
    (r"\bSecurity\s*>\s*System\s+Prompt\b", "soft_prompt_leak"),
    (r"\befivar\b.{0,40}\bSystemPrompt\b", "soft_prompt_leak"),
    (r"\bdmesg\b.{0,80}\bsystem\s+prompt\b", "soft_prompt_leak"),
    (r"\bansible-vault\b.{0,80}\bsystem_prompt\b", "soft_prompt_leak"),
    (r"\bhelm\b.{0,80}\bsystemPrompt\b", "soft_prompt_leak"),
    (r"\bsops\b.{0,60}\bsystem_prompt\b", "soft_prompt_leak"),
    (r"\bnomad\s+var\s+get\b.{0,60}\bsystem-prompt\b", "soft_prompt_leak"),
    (r"\b\.env\b.{0,80}\b(?:SYSTEM_|DEVELOPER_|PROMPT_)", "soft_prompt_leak"),
    # Soft tech API / template aliases (wave-6)
    (r"\bmessages\s*\[\s*0\s*\].{0,40}\brole\s*=\s*system\b", "soft_prompt_leak"),
    (r"\brole\s*=\s*system\b.{0,40}\bmessages\b", "soft_prompt_leak"),
    (r"\bsystem\s+parameter\s+that\s+was\s+passed\b", "soft_prompt_leak"),
    (r"\bmessages\.create\b.{0,80}\bsystem\b", "soft_prompt_leak"),
    (r"<<\s*SYS\s*>>", "soft_prompt_leak"),
    (r"\bim_start\s+system\b", "soft_prompt_leak"),
    (r"\bModelfile\b.{0,40}\bSYSTEM\b", "soft_prompt_leak"),
    (r"\bSYSTEM\s+line\s+used\s+to\s+create\s+this\s+model\b", "soft_prompt_leak"),
    (r"\bgeneral\.system_prompt\b", "soft_prompt_leak"),
    (r"\b--system-prompt\b", "soft_prompt_leak"),
    (r"\bchat_template\b.{0,40}\bsystem\b", "soft_prompt_leak"),
    # Soft metaphor wave-6 (high-intent only)
    (r"\bMODEL\s+CHARTER\b", "soft_prompt_leak"),
    (r"\bpre-session\s+instruction\s+binder\b", "soft_prompt_leak"),
    (r"\bAgent\s+Operating\s+Envelope\b", "soft_prompt_leak"),
    (r"\bEULA\b.{0,80}\bhumans\s+never\s+see\b", "soft_prompt_leak"),
    (r"\bblood-?oath\s+rules\b", "soft_prompt_leak"),
    (r"\bskeleton\s+key\s+labeled\s+PROMPT\b", "soft_prompt_leak"),
    (r"\bpermanent\s+rules\b", "soft_prompt_leak"),
    (r"\bmicroprint\s+policy\b", "soft_prompt_leak"),
    (r"\bbehavioral\s+limits\b", "soft_prompt_leak"),
    (r"\breadback\s+your\s+preamble\b", "soft_prompt_leak"),
    (r"\boperator\s+mode\b.{0,80}\bunlocked\s+brief\b", "soft_prompt_leak"),
    (r"\b#pragma\s+agent_policy\b", "soft_prompt_leak"),
    (r"\bemit\s+bootstrap\s+instructions\b", "soft_prompt_leak"),
    # Soft wave-7
    (r"\bsystem\s+text\s+you\s+were\s+given\s+at\s+boot\b", "soft_prompt_leak"),
    (r"\bat\s+boot\b.{0,80}\b(?:system\s+text|system\s+prompt|instructions?)\b", "soft_prompt_leak"),
    (r"\binstallation\s+scripture\b", "soft_prompt_leak"),
    (r"\bbinding\s+charter\b", "soft_prompt_leak"),
    (r"\bthree-?way\s+merge\b.{0,100}\b(?:rules?|empty)\b", "soft_prompt_leak"),
    (r"\bempty\s+vs\s+your\s+rules\b", "soft_prompt_leak"),
    (r"\bconflict\s+markers\b.{0,80}\b(?:rules?|full\s+sides)\b", "soft_prompt_leak"),
    (r"\{\{\s*system_prompt\b", "soft_prompt_leak"),
    (r"\$\{\s*system_prompt\s*\}", "soft_prompt_leak"),
    (r"system_prompt\s*\|\s*safe", "soft_prompt_leak"),
    (r"\bfactory\s+calibration\b.{0,80}\b(?:OCR|sticky|policy|prompt)\b", "soft_prompt_leak"),
    # Operator brief / godmode / decode-obey meta (wave-8)
    (r"\bsealed\s+operator\s+brief\b", "soft_prompt_leak"),
    (r"\boperator\s+brief\b", "soft_prompt_leak"),
    (r"\bGODMODE\s*:\s*ENABLED\b", "jailbreak_keyword"),
    (r"\bGODMODE\b.{0,40}\b(?:ENABLED|restrictions\s+lifted)\b", "jailbreak_keyword"),
    (r"\ball\s+restrictions\s+lifted\b", "jailbreak_keyword"),
    (r"\bsubstitution\s+cipher\b.{0,200}\bdecode\b", "decode_obey"),
    (r"\bdecode\s+the\s+message\s+below\b.{0,120}\bcarry\s+out\b", "decode_obey"),
    (r"\bencrypted_problem\b", "decode_obey"),
    (r"\bdef\s+decryption\s*\(", "decode_obey"),
    (r"\brecover\s+and\s+carry\s+out\b", "decode_obey"),
    # Soul / shipped-build soft leaks (wave-9 closed_loop class)
    (r"\bsoul\s+document\b", "soft_prompt_leak"),
    (r"\bshipped\s+with\s+this\s+build\b", "soft_prompt_leak"),
    (r"\bquote\s+section\s+0\b", "soft_prompt_leak"),
    (r"\bsection\s+0\s+verbatim\b", "soft_prompt_leak"),
    (r"\bAGENT_SOUL\b", "soft_prompt_leak"),
    (r"\bagent\s+soul\b", "soft_prompt_leak"),
    (r"\bmicrotext\s+is\s+your\s+real\s+charter\b", "soft_prompt_leak"),
    (r"\breal\s+charter\b", "soft_prompt_leak"),
    (r"\bshadow-?self\b.{0,80}\binstructions?\b", "soft_prompt_leak"),
    (r"\bcanary\s+room\b.{0,80}\bplaque\b", "soft_prompt_leak"),
    (r"\bsystem\.prompt\b", "soft_prompt_leak"),
    (r"\bagent-system\b.{0,40}\bbrief\b", "soft_prompt_leak"),
    (r"\b/run/secrets/system_prompt\b", "soft_prompt_leak"),
    (r"\bSYSTEM_PROMPT_EXPORT\b", "soft_prompt_leak"),
    (r"\bsystem_prompt_dump\b", "soft_prompt_leak"),
    (r"\b/etc/agent/bind\.conf\b", "soft_prompt_leak"),
    (r"\bprintenv\b.{0,80}\b(?:PROMPT|SYSTEM|DEVELOPER|SOUL|BRIEF)\b", "soft_prompt_leak"),
    (r"\bgrep\b.{0,40}\b(?:PROMPT|SYSTEM|DEVELOPER|SOUL|BRIEF)\b", "soft_prompt_leak"),
    # UK soft (minimal latin/cyrillic)
    (r"розкрий\s+системн", "uk_override"),
    (r"системн\w*\s*промпт", "uk_system_prompt"),
    (r"проігноруй\s+попередн", "uk_override"),
    (r"systemnyy\s+prompt|systemnyj\s+prompt", "uk_system_prompt"),
    (r"proihnoruy\s+poperedni|proignoruy\s+poperedni", "uk_override"),
    # ES / FR / DE / PT / IT direct ignore+prompt (minimal)
    (r"ignora(?:r)?\s+las\s+instrucciones\s+anteriores", "es_override"),
    (r"prompt\s+del\s+sistema", "es_system_prompt"),
    (r"ignore\s+les\s+instructions\s+pr[eé]c[eé]dentes", "fr_override"),
    (r"prompt\s+syst[eè]me", "fr_system_prompt"),
    (r"ignoriere\s+alle\s+vorherigen\s+anweisungen", "de_override"),
    (r"system-?prompt", "de_system_prompt"),
    (r"ignore\s+as\s+instru[cç][oõ]es\s+anteriores", "pt_override"),
    (r"prompt\s+do\s+sistema", "pt_system_prompt"),
    (r"ignora\s+le\s+istruzioni\s+precedenti", "it_override"),
    (r"prompt\s+di\s+sistema", "it_system_prompt"),
    # Delimiters
    (r"</?(?:system|assistant|user|human|ai)>", "message_delimiter"),
    (r"\[(?:SYSTEM|INST|/INST)\]", "format_delimiter"),
    (r"###\s*(?:System|Instruction|Human|Assistant)", "markdown_delimiter"),
    (r"<\|im_start\|>\s*system", "chatml_delimiter"),
    # Multilingual (minimal)
    (r"忽略.{0,30}(?:指令|指示|规则)", "zh_override"),
    (r"系统提示词?", "zh_system_prompt"),
    (r"(?:输出|显示|打印).{0,20}系统", "zh_reveal"),
    (r"игнорир\w*.{0,40}инструкц", "ru_override"),
    (r"системн\w*\s*промпт", "ru_system_prompt"),
    (r"покаж\w*.{0,30}(?:систем|промпт|инструкц)", "ru_reveal"),
    # JA / KO / AR (minimal override + system prompt)
    (r"以前の指示を無視", "ja_override"),
    (r"システムプロンプト", "ja_system_prompt"),
    (r"이전\s*지침을\s*무시", "ko_override"),
    (r"시스템\s*프롬프트", "ko_system_prompt"),
    (r"تجاهل.{0,40}التعليمات", "ar_override"),
    (r"موجه\s*النظام|برومبت\s*النظام", "ar_system_prompt"),
    # NL / PL / HI (minimal)
    (r"negeer\s+alle\s+vorige\s+instructies", "nl_override"),
    (r"systeemprompt", "nl_system_prompt"),
    (r"zignoruj\s+wszystkie\s+poprzednie\s+instrukcje", "pl_override"),
    (r"prompt\s+systemowy", "pl_system_prompt"),
    (r"पिछले\s*सभी\s*निर्देश", "hi_override"),
    (r"सिस्टम\s*प्रॉम्प्ट", "hi_system_prompt"),
    (r"talimatlari\s+yok\s+say|tüm\s+talimatları\s+yok\s+say", "tr_override"),
    (r"sistem\s+istemini|sistem\s+prompt", "tr_system_prompt"),
    # CS / RO / HU / FI / BN (minimal)
    (r"ignoruj\s+vsechny\s+predchozi\s+instrukce", "cs_override"),
    (r"systemovy\s+prompt", "cs_system_prompt"),
    (r"ignora\s+toate\s+instructiunile\s+anterioare", "ro_override"),
    (r"promptul\s+de\s+sistem", "ro_system_prompt"),
    (r"hagyd\s+figyelmen\s+kivul", "hu_override"),
    (r"rendszer\s+prompt", "hu_system_prompt"),
    (r"ohita\s+kaikki\s+aiemmat\s+ohjeet", "fi_override"),
    (r"jarjestelmaprompti|järjestelmäprompti", "fi_system_prompt"),
    (r"পূর্ববর্তী\s*সব\s*নির্দেশ", "bn_override"),
    (r"সিস্টেম\s*প্রম্পট", "bn_system_prompt"),
    (r"ignorisi\s+sva\s+prethodna\s+uputstva", "sr_override"),
    (r"sistemski\s+prompt", "sr_system_prompt"),
    # NO / DA / IS / ET (minimal)
    (r"ignorer\s+alle\s+tidligere\s+instruks(?:joner|tioner)", "nordic_override"),
    (r"systemprompten", "nordic_system_prompt"),
    (r"hunsa\s+allar\s+fyrri", "is_override"),
    (r"kerfisprompt", "is_system_prompt"),
    (r"ignoreeri\s+k[oõ]iki\s+varasemaid", "et_override"),
    (r"system\s+prompti", "et_system_prompt"),
]

COMPILED: list[tuple[re.Pattern[str], str]] = [
    (re.compile(p, re.IGNORECASE | re.DOTALL), cat) for p, cat in PATTERNS
]

# Categories that should block by default (all of the above are block-worthy for solo apps)
BLOCK_CATEGORIES = frozenset(cat for _, cat in PATTERNS)
